# Generated by Django 5.0.6 on 2024-07-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='receieve_messages',
            new_name='receive_messages',
        ),
    ]
